run:
  issues-exit-code: #Default
  tests: true #Default

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unused
    - whitespace

linter-settings:
  gofmt:
    simplify: true

issues: 
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck