language: go

os:
  - linux
  - osx
  
go: 1.8

install:
  - go get -v -t .
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports
  
script:
 - go vet ./...
 - diff <(goimports -d .) <(printf "")
 - diff <(golint ./...) <(printf "")
  
