language: go

os:
  - linux
  - osx
  
go: 1.8

install:
  - go get -v -t .
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports
  
script:
 - go vet ./...
 - diff <(golint ./...) <(printf "")
 - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
