language: go

os:
  - linux
  
go: 
  - "1.17.x"
  - tip

install:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint 

script:
 - ./test.sh
 - golangci-lint run

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
