version: "{build}"

build: off

clone_folder: c:\github.com\bvwells\go-patterns

stack: go 1.17.1

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env

test_script:
 - go test -race -v ./...
