version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\github.com\bvwells\go-patterns

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env

build_script:
 - go install -v ./...

test_script:
 - go test -race -v ./...
